//
//  LogicCommands.swift
//  AGI
//
//  Created by Phil Inglis on 2022-03-30.
//

import Foundation

struct LogicCode {
    let name: String
    let numberOfArguments: Int
}

enum CodeName: UInt8 {
    case codeIf = 0xFF
    case codeElse = 0xFE
    case codeNot = 0xFD
    case codeOr = 0xFC
    case codeSaid = 0x0E
}

class LogicCodes {
    
    // Control Code
    static let controlCodes: [UInt8: LogicCode] = [
        
        0xFF: LogicCode(name: "if", numberOfArguments: 0),
        0xFE: LogicCode(name: "else", numberOfArguments: 0),
        0xFD: LogicCode(name: "not", numberOfArguments: 0),
        0xFC: LogicCode(name: "or", numberOfArguments: 0)
    ]
    
    // Condition Codes
    static let conditionCodes: [UInt8: LogicCode] = [
        
        0x00: LogicCode(name: "unknown", numberOfArguments: 0),
        0x01: LogicCode(name: "equal", numberOfArguments: 2),
        0x02: LogicCode(name: "equal.v", numberOfArguments: 2),
        0x03: LogicCode(name: "less", numberOfArguments: 2),
        0x04: LogicCode(name: "less.v", numberOfArguments: 2),
        0x05: LogicCode(name: "greater", numberOfArguments: 2),
        0x06: LogicCode(name: "greater.v", numberOfArguments: 2),
        0x07: LogicCode(name: "isset", numberOfArguments: 1),
        0x08: LogicCode(name: "isset.v", numberOfArguments: 1),
        0x09: LogicCode(name: "has", numberOfArguments: 1),
        0x0A: LogicCode(name: "obj.in.room", numberOfArguments: 2),
        0x0B: LogicCode(name: "position", numberOfArguments: 5),
        0x0C: LogicCode(name: "controller", numberOfArguments: 1),
        0x0D: LogicCode(name: "have.key", numberOfArguments: 0),
        0x0E: LogicCode(name: "said", numberOfArguments: -1),
        0x0F: LogicCode(name: "compare.strings", numberOfArguments: 2),
        0x10: LogicCode(name: "obj.in.box", numberOfArguments: 5),
        0x11: LogicCode(name: "center.position", numberOfArguments: 5),
        0x12: LogicCode(name: "right.position", numberOfArguments: 5),
        0x13: LogicCode(name: "in.motion.using.mouse", numberOfArguments: 0)
    ]
    
    // Operation Codes
    static let operationCodes: [UInt8: LogicCode] = [
        
        0x00: LogicCode(name: "return", numberOfArguments: 0),
        0x01: LogicCode(name: "increment", numberOfArguments: 1),
        0x02: LogicCode(name: "decrement", numberOfArguments: 1),
        0x03: LogicCode(name: "assign", numberOfArguments: 2),
        0x04: LogicCode(name: "assign.v", numberOfArguments: 2),
        0x05: LogicCode(name: "add", numberOfArguments: 2),
        0x06: LogicCode(name: "add.v", numberOfArguments: 2),
        0x07: LogicCode(name: "sub", numberOfArguments: 2),
        0x08: LogicCode(name: "sub.v", numberOfArguments: 2),
        0x09: LogicCode(name: "lindirect.v", numberOfArguments: 2),
        0x0A: LogicCode(name: "lindirect", numberOfArguments: 2),
        0x0B: LogicCode(name: "lindirect.n", numberOfArguments: 2),
        0x0C: LogicCode(name: "set", numberOfArguments: 1),
        0x0D: LogicCode(name: "reset", numberOfArguments: 1),
        0x0E: LogicCode(name: "toggle", numberOfArguments: 1),
        0x0F: LogicCode(name: "set.v", numberOfArguments: 1),
        0x10: LogicCode(name: "reset.v", numberOfArguments: 1),
        0x11: LogicCode(name: "toggle.v", numberOfArguments: 1),
        0x12: LogicCode(name: "new.room", numberOfArguments: 1),
        0x13: LogicCode(name: "new.room.v", numberOfArguments: 1),
        0x14: LogicCode(name: "load.logics", numberOfArguments: 1),
        0x15: LogicCode(name: "load.logics.v", numberOfArguments: 1),
        0x16: LogicCode(name: "call", numberOfArguments: 1),
        0x17: LogicCode(name: "call.v", numberOfArguments: 1),
        0x18: LogicCode(name: "load.pic", numberOfArguments: 1),
        0x19: LogicCode(name: "draw.pic", numberOfArguments: 1),
        0x1A: LogicCode(name: "show.pic", numberOfArguments: 0),
        0x1B: LogicCode(name: "discard.pic", numberOfArguments: 1),
        0x1C: LogicCode(name: "overlay.pic", numberOfArguments: 1),
        0x1D: LogicCode(name: "show.pri.screen", numberOfArguments: 0),
        0x1E: LogicCode(name: "load.view", numberOfArguments: 1),
        0x1F: LogicCode(name: "load.view.v", numberOfArguments: 1),
        0x20: LogicCode(name: "discard.view", numberOfArguments: 1),
        0x21: LogicCode(name: "animate.obj", numberOfArguments: 1),
        0x22: LogicCode(name: "unanimate.all", numberOfArguments: 0),
        0x23: LogicCode(name: "draw", numberOfArguments: 1),
        0x24: LogicCode(name: "erase", numberOfArguments: 1),
        0x25: LogicCode(name: "position", numberOfArguments: 3),
        0x26: LogicCode(name: "position.v", numberOfArguments: 3),
        0x27: LogicCode(name: "get.posn", numberOfArguments: 3),
        0x28: LogicCode(name: "reposition", numberOfArguments: 3),
        0x29: LogicCode(name: "set.view", numberOfArguments: 2),
        0x2A: LogicCode(name: "set.view.v", numberOfArguments: 2),
        0x2B: LogicCode(name: "set.loop", numberOfArguments: 2),
        0x2C: LogicCode(name: "set.loop.v", numberOfArguments: 2),
        0x2D: LogicCode(name: "fix.loop", numberOfArguments: 1),
        0x2E: LogicCode(name: "release.loop", numberOfArguments: 1),
        0x2F: LogicCode(name: "set.cel", numberOfArguments: 2),
        0x30: LogicCode(name: "set.cel.v", numberOfArguments: 2),
        0x31: LogicCode(name: "last.cel", numberOfArguments: 2),
        0x32: LogicCode(name: "current.cel", numberOfArguments: 2),
        0x33: LogicCode(name: "current.loop", numberOfArguments: 2),
        0x34: LogicCode(name: "current.view", numberOfArguments: 2),
        0x35: LogicCode(name: "number.of.loops", numberOfArguments: 2),
        0x36: LogicCode(name: "set.priority", numberOfArguments: 2),
        0x37: LogicCode(name: "set.priority.v", numberOfArguments: 2),
        0x38: LogicCode(name: "release.priority", numberOfArguments: 1),
        0x39: LogicCode(name: "get.priority.v", numberOfArguments: 2),
        0x3A: LogicCode(name: "stop.update", numberOfArguments: 1),
        0x3B: LogicCode(name: "start.update", numberOfArguments: 1),
        0x3C: LogicCode(name: "force.update", numberOfArguments: 1),
        0x3D: LogicCode(name: "ignore.horizon", numberOfArguments: 1),
        0x3E: LogicCode(name: "observe.horizon", numberOfArguments: 1),
        0x3F: LogicCode(name: "set.horizon", numberOfArguments: 1),
        0x40: LogicCode(name: "object.on.water", numberOfArguments: 1),
        0x41: LogicCode(name: "object.on.land", numberOfArguments: 1),
        0x42: LogicCode(name: "object.on.anything", numberOfArguments: 1),
        0x43 : LogicCode(name: "ignore.objs", numberOfArguments: 1),
        0x44: LogicCode(name: "observe.objs", numberOfArguments: 1),
        0x45: LogicCode(name: "distance", numberOfArguments: 3),
        0x46: LogicCode(name: "stop.cycling", numberOfArguments: 1),
        0x47: LogicCode(name: "start.cycling", numberOfArguments: 1),
        0x48: LogicCode(name: "normal.cycle", numberOfArguments: 1),
        0x49: LogicCode(name: "end.of.loop", numberOfArguments: 2),
        0x4A: LogicCode(name: "reverse.cycle", numberOfArguments: 1),
        0x4B: LogicCode(name: "reverse.loop", numberOfArguments: 2),
        0x4C: LogicCode(name: "cycle.time", numberOfArguments: 2),
        0x4D: LogicCode(name: "stop.motion", numberOfArguments: 1),
        0x4E: LogicCode(name: "start.motion", numberOfArguments: 1),
        0x4F: LogicCode(name: "step.size", numberOfArguments: 2),
        0x50: LogicCode(name: "step.time", numberOfArguments: 2),
        0x51: LogicCode(name: "move.obj", numberOfArguments: 5),
        0x52: LogicCode(name: "move.obj.v", numberOfArguments: 5),
        0x53: LogicCode(name: "follow.ego", numberOfArguments: 3),
        0x54: LogicCode(name: "wander", numberOfArguments: 1),
        0x55: LogicCode(name: "normal.motion", numberOfArguments: 1),
        0x56: LogicCode(name: "set.dir", numberOfArguments: 2),
        0x57: LogicCode(name: "get.dir", numberOfArguments: 2),
        0x58: LogicCode(name: "ignore.blocks", numberOfArguments: 1),
        0x59: LogicCode(name: "observe.blocks", numberOfArguments: 1),
        0x5A: LogicCode(name: "block", numberOfArguments: 4),
        0x5B: LogicCode(name: "unblock", numberOfArguments: 0),
        0x5C: LogicCode(name: "get", numberOfArguments: 1),
        0x5D: LogicCode(name: "get.v", numberOfArguments: 1),
        0x5E: LogicCode(name: "drop", numberOfArguments: 1),
        0x5F: LogicCode(name: "put", numberOfArguments: 2),
        0x60: LogicCode(name: "put.v", numberOfArguments: 2),
        0x61: LogicCode(name: "get.room.v", numberOfArguments: 2),
        0x62: LogicCode(name: "load.sound", numberOfArguments: 1),
        0x63: LogicCode(name: "sound", numberOfArguments: 2),
        0x64: LogicCode(name: "stop.sound", numberOfArguments: 0),
        0x65: LogicCode(name: "print", numberOfArguments: 1),
        0x66: LogicCode(name: "print.v", numberOfArguments: 1),
        0x67: LogicCode(name: "display", numberOfArguments: 3),
        0x68: LogicCode(name: "display.v", numberOfArguments: 3),
        0x69: LogicCode(name: "clear.lines", numberOfArguments: 3),
        0x6A: LogicCode(name: "text.screen", numberOfArguments: 0),
        0x6B: LogicCode(name: "graphics", numberOfArguments: 0),
        0x6C: LogicCode(name: "set.cursor.char", numberOfArguments: 1),
        0x6D: LogicCode(name: "set.text.attribute", numberOfArguments: 2),
        0x6E: LogicCode(name: "shake.sceen", numberOfArguments: 1),
        0x6F: LogicCode(name: "configure.sceen", numberOfArguments: 3),
        0x70: LogicCode(name: "status.line.on", numberOfArguments: 0),
        0x71: LogicCode(name: "status.line.off", numberOfArguments: 0),
        0x72: LogicCode(name: "set.string", numberOfArguments: 2),
        0x73: LogicCode(name: "get.string", numberOfArguments: 5),
        0x74: LogicCode(name: "word.to.string", numberOfArguments: 2),
        0x75: LogicCode(name: "parse", numberOfArguments: 1),
        0x76: LogicCode(name: "get.num", numberOfArguments: 2),
        0x77: LogicCode(name: "prevent.input", numberOfArguments: 0),
        0x78: LogicCode(name: "accept.input", numberOfArguments: 0),
        0x79: LogicCode(name: "set.key", numberOfArguments: 3),
        0x7A: LogicCode(name: "add.to.pic", numberOfArguments: 7),
        0x7B: LogicCode(name: "add.to.pic.v", numberOfArguments: 7),
        0x7C: LogicCode(name: "status", numberOfArguments: 0),
        0x7D: LogicCode(name: "save.game", numberOfArguments: 0),
        0x7E: LogicCode(name: "restore.game", numberOfArguments: 0),
        0x7F: LogicCode(name: "init.disk", numberOfArguments: 0),
        0x80: LogicCode(name: "restart.game", numberOfArguments: 0),
        0x81: LogicCode(name: "show.obj", numberOfArguments: 1),
        0x82: LogicCode(name: "random", numberOfArguments: 3),
        0x83: LogicCode(name: "program.control", numberOfArguments: 0),
        0x84: LogicCode(name: "player.control", numberOfArguments: 0),
        0x85: LogicCode(name: "obj.status.v", numberOfArguments: 1),
        0x86: LogicCode(name: "quit", numberOfArguments: 1),
        0x87: LogicCode(name: "show.mem", numberOfArguments: 0),
        0x88: LogicCode(name: "pause", numberOfArguments: 0),
        0x89: LogicCode(name: "echo.line", numberOfArguments: 0),
        0x8A: LogicCode(name: "cancel.line", numberOfArguments: 0),
        0x8B: LogicCode(name: "init.joy", numberOfArguments: 0),
        0x8C: LogicCode(name: "toggle.monitor", numberOfArguments: 0),
        0x8D: LogicCode(name: "version", numberOfArguments: 0),
        0x8E: LogicCode(name: "script.size", numberOfArguments: 1),
        0x8F: LogicCode(name: "set.game.id", numberOfArguments: 1),
        0x90: LogicCode(name: "log", numberOfArguments: 1),
        0x91: LogicCode(name: "set.scan.start", numberOfArguments: 0),
        0x92: LogicCode(name: "reset.scan.start", numberOfArguments: 0),
        0x93: LogicCode(name: "reposition.to", numberOfArguments: 3),
        0x94: LogicCode(name: "reposition.to.v", numberOfArguments: 3),
        0x95: LogicCode(name: "trace.on", numberOfArguments: 0),
        0x96: LogicCode(name: "trace.info", numberOfArguments: 3),
        0x97: LogicCode(name: "print.at", numberOfArguments: 4),
        0x98: LogicCode(name: "print.at.v", numberOfArguments: 4),
        0x99: LogicCode(name: "discard.view.v", numberOfArguments: 1),
        0x9A: LogicCode(name: "clear.text.rect", numberOfArguments: 5),
        0x9B: LogicCode(name: "set.upper.left", numberOfArguments: 2),
        0x9C: LogicCode(name: "set.menu", numberOfArguments: 1),
        0x9D: LogicCode(name: "set.menu.item", numberOfArguments: 2),
        0x9E: LogicCode(name: "submit.menu", numberOfArguments: 0),
        0x9F: LogicCode(name: "enable.item", numberOfArguments: 1),
        0xA0: LogicCode(name: "disable.item", numberOfArguments: 1),
        0xA1: LogicCode(name: "menu.input", numberOfArguments: 0),
        0xA2: LogicCode(name: "show.obj.v", numberOfArguments: 1),
        0xA3: LogicCode(name: "open.dialog", numberOfArguments: 0),
        0xA4: LogicCode(name: "close.dialog", numberOfArguments: 0),
        0xA5: LogicCode(name: "mul.n", numberOfArguments: 2),
        0xA6: LogicCode(name: "mul.v", numberOfArguments: 2),
        0xA7: LogicCode(name: "div.n", numberOfArguments: 2),
        0xA8: LogicCode(name: "div.v", numberOfArguments: 2),
        0xA9: LogicCode(name: "close.window", numberOfArguments: 0),
        0xAA: LogicCode(name: "set.simple", numberOfArguments: 1),
        0xAB: LogicCode(name: "push.script", numberOfArguments: 0),
        0xAC: LogicCode(name: "pop.script", numberOfArguments: 0),
        0xAD: LogicCode(name: "hold.key", numberOfArguments: 0),
        0xAE: LogicCode(name: "set.pri.base", numberOfArguments: 1),
        0xAF: LogicCode(name: "discard.sound", numberOfArguments: 1),
        0xB0: LogicCode(name: "hide.mouse", numberOfArguments: 0),
        0xB1: LogicCode(name: "allow.menu", numberOfArguments: 1),
        0xB2: LogicCode(name: "show.mouse", numberOfArguments: 0),
        0xB3: LogicCode(name: "fence.mouse", numberOfArguments: 4),
        0xB4: LogicCode(name: "mouse.position", numberOfArguments: 2),
        0xB5: LogicCode(name: "release.key", numberOfArguments: 0),
        0xB6: LogicCode(name: "adj.ego.move.to.xy", numberOfArguments: 0),
        0xFE: LogicCode(name: "go.to", numberOfArguments: 2)
    ]
}
